### ISSUE TITLE
Atualização do RoadMap  

### ISSUE THREAD

**Issue by JeffersonSenaa** [ResidenciaTICBrisa/T2G7-Revista-Darcy#87]
## Descrição 
O RoadMap foi atualizado descrevendoas novas etapas para as próximas sprints e releases. Dentre as mudanças, está a organização do cronograma seguindo o período de desenvolvimento do site em ambiente de homologação e o período previsto para implementação do site em ambiente de produção. 

## Tarefas
Etapas necessárias para resolução do problema:

- [x] Atualização de metas das Sprints
- [x] Atualização de Cronograma

## Critérios de Aceitação

- [x] As mudanças podem ser visualizadas no MKDocs

## Recursos
https://residenciaticbrisa.github.io/T2G7-Revista-Darcy/requisitos/visao_de_projeto/#2-planejamento-das-sprints-do-projeto
